name: Deploy ImageDetectionTests

on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup .Net 
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.0
      - name: Install Packages
        run: sudo apt-get install uuid-runtime
      - name: Install Workload
        run: dotnet workload install wasm-tools
      - name: Publish
        working-directory: ./Server
        run: dotnet publish -c Release -o Release --self-contained true -r linux-x64 ImageDetectionTests.Server.csproj
      - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
        working-directory: ./Server
        run: sed -i 's/<base href="\/" \/>/<base href="\/ImageDetectionTests\/" \/>/g' ./Release/wwwroot/index.html
      - name: Change version in index.html to not use cached data
        working-directory: ./Server
        run: sed -i 's/{version}/$(uuidgen)/g' ./Release/wwwroot/index.html
      - name: Add .nojekyll file
        working-directory: ./Server
        run: touch ./Release/wwwroot/.nojekyll
      - name: copy index.html to 404.html
        working-directory: ./Server
        run: cp Release/wwwroot/index.html Release/wwwroot/404.html
      - name: Copy wwwroot to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: Server/Release/wwwroot
